POST https://api.dada-tuda.ru/api/v1/feedback
Content-Type: application/json

{
  "eventId": "KG216643",
  "like": "true",
  "viewedSeconds": "1",
  "moreOpened": "true",
  "reported": "false",
  "userId": "1488"
}

